apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rest-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-rest-operator
  template:
    metadata:
      labels:
        name: k8s-rest-operator
    spec:
      serviceAccountName: k8s-rest-operator
      containers:
        - name: k8s-rest-operator
          image: quay.io/cmit/k8s-rest-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-rest-operator"
